### ISSUE TITLE
error import OPML

### ISSUE THREAD

**Issue by amigo421** [luyuhuang/vscode-rss#28]
latest stable vscode 
1. exported OPML from inoreader 
2. tried to import into the extension 
3. got "bad OPML format" (other RSS readers could import this without issues)

**Comment by amigo421** [comment]
to avoid a lot of request, just one issue with the extension for me:
two machines: comp1 and comp2
1. added 10+ feeds locally on comp1
2. the feeds were sycned on comp2  via settings and github account
3. comp2 shows me news well, but comp1 does no, something happened with extension
4. comp1: feeds in settings sync and equal to comp2 (where it works) 
5. extension doesn't work on comp1 even to add one more feed: I'm clicking on "+" - add an account and nothing happens , other extension buttons don't work too

any idea how to reset extension?

**Comment by luyuhuang** [comment]
> to avoid a lot of requests, just one issue with the extension for me:
> two machines: comp1 and comp2
> 1. added 10+ feeds locally on comp1
> ...

That sounds weird. I tried these steps and there no such problem. Does the problem still exist after restarting vscode? If so, click Help -> Toggle Developer Tools and check if has any errors. If you want to reset the extension, uninstall the extension, reload vscode, and then re-install the extension.

**Comment by amigo421** [comment]
Hi 
thank you for the response.
1. of course, I've already tried to uninstall and restart and tried one more time for sure. it doesn't help: still no any effect on RSS ext buttons clicking
2. I'm not vscode code and not sure what do you mean "config.json" , probably settings.json? if no - please let me know where I can look for config.json
3. The same for dev mode, I can open this but could not find where logs can be there... please specify.

regarding initial question about OPML - if you can't reproduce please let me know , I can share my OPML , nothing confidential just a few C++ dev channels

**Comment by luyuhuang** [comment]
> 2. I'm not vscode coder and not sure what do you mean "config.json" , probably settings.json? if no - please let me know where I can look for config.json
>
> Update : seems solved - found the folder: C:\Users<USER>\AppData\Roaming\Code\User\globalStorage and your extension subfolder contained 6 subfolders. deleted all this and restarted vscode...

Oh, sorry, I mean `settings.json`. But anyway I want to know why it doesn't work. Could you show me the content in `settings.json`? Besides, if the 6 subfolders are still in your Recycle Bin, I want to know their name.

> regarding initial question about OPML - if you can't reproduce please let me know , I can share my OPML , nothing confidential just a few C++ dev channels

Of course, It's a bug that should be resolved. It would be better if you can share the OPML.

**Comment by luyuhuang** [comment]
> 3. The same for dev mode, I can open this but could not find where logs can be there... please specify.

To open the console:

![console](https://user-images.githubusercontent.com/10300685/106863259-3499f580-6703-11eb-851d-6edebf2eb2ce.gif)

**Comment by amigo421** [comment]
thank you , let me collect folder names, actually I could restore and share those for you? 

one more question: this rss source is not resolved by the extension: http://scrutator.me/syndication.axd

**Comment by luyuhuang** [comment]
> thank you , let me collect folder names, actually I could restore and share those for you?

Thank you, that would be very helpful. you can send it to my email luyu_huang@foxmail.com

> one more question: this rss source is not resolved by the extension: http://scrutator.me/syndication.axd

Seems to be another bug. Could you open an new issue?

**Comment by amigo421** [comment]
raised #29 

will send you a folders to email soon

**Comment by luyuhuang** [comment]
Thanks a lot!

**Comment by amigo421** [comment]
the sync process between two machines still has an issue. I'll raise separate ticket with a description.
